# Use the token for this service account to authenticate o-neko against the k8s cluster. Find the token with:
# kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep o-neko | awk '{print $1}')
apiVersion: v1
kind: ServiceAccount
metadata:
  name: o-neko
  namespace: kube-system